/*
 * _7_seg.c
 *
 * Created: 1/8/2021 11:49:53 PM
 *  Author: mostafa gomaa
 */ 

#include "seg.h"

void SEG_INIT(void)
{
	#if MODE == DCB_MODE
	 
	 DIO_SETPINDIR(DATA_PORT , DATA_PINA , DIO_PIN_OUTPUT);
	 DIO_SETPINDIR(DATA_PORT , DATA_PINB , DIO_PIN_OUTPUT);
	 DIO_SETPINDIR(DATA_PORT , DATA_PINC , DIO_PIN_OUTPUT);
	 DIO_SETPINDIR(DATA_PORT , DATA_PIND , DIO_PIN_OUTPUT);
	 
	 DIO_SETPINDIR(EN_PORT , EN1_PIN , DIO_PIN_OUTPUT);
	 DIO_SETPINDIR(EN_PORT , EN2_PIN , DIO_PIN_OUTPUT);
	 
	#elif  MODE == NORMAL_MODE
	
	DIO_SETPORTDIR(DATA_PORT , DIO_PORT_OUTPUT);
	
    DIO_SETPINDIR(EN_PORT , EN1_PIN , DIO_PIN_OUTPUT);
    DIO_SETPINDIR(EN_PORT , EN2_PIN , DIO_PIN_OUTPUT);
	#endif
}

void SEG_DISPLAY(u_int8 num)
{
	#if MODE == DCB_MODE
	
	PORTA = (PORTA & 0x0F) | (((num / 10) << 4) & 0xF0);
	
	DIO_SETPINVAL(EN_PORT , EN1_PIN , DIO_PIN_HIGH);
	_delay_ms(10);
	DIO_SETPINVAL(EN_PORT , EN1_PIN , DIO_PIN_LOW);
	
	PORTA = (PORTA & 0x0F) | (((num % 10) << 4) & 0xF0);
	
	DIO_SETPINVAL(EN_PORT , EN2_PIN , DIO_PIN_HIGH);
	_delay_ms(10);
	DIO_SETPINVAL(EN_PORT , EN2_PIN , DIO_PIN_LOW);
	
	#elif  MODE == NORMAL_MODE
	
	DATA_PORT_VAL = ( num / 10 );
	
	DIO_SETPINVAL(EN_PORT , EN1_PIN , DIO_PIN_HIGH);
	_delay_ms(10);
	DIO_SETPINVAL(EN_PORT , EN1_PIN , DIO_PIN_LOW);
	
	DATA_PORT_VAL = ( num % 10 );
	
	DIO_SETPINVAL(EN_PORT , EN1_PIN , DIO_PIN_HIGH);
	_delay_ms(10);
	DIO_SETPINVAL(EN_PORT , EN1_PIN , DIO_PIN_LOW);
	 
	#endif
	
}